export type Lang = "en" | "ar";

const dict = {
  // nav
  home: { en: "Home", ar: "الرئيسية" },
  ourStory: { en: "Our Story", ar: "قصتنا" },
  memories: { en: "Memories", ar: "ذكرياتنا" },
  eventDetails: { en: "Event Details", ar: "تفاصيل الحفل" },
  invitations: { en: "Invitations", ar: "الدعوات" },
  rsvp: { en: "RSVP", ar: "تأكيد الحضور" },
  switchStyle: { en: "Switch Style", ar: "تغيير التصميم" },
  close: { en: "Close", ar: "إغلاق" },
  language: { en: "العربية", ar: "English" },

  // hero
  weAreMarrying: { en: "We are getting married", ar: "نحن نحتفل بزواجنا" },
  scrollExplore: { en: "Scroll to explore", ar: "مرّر للاستكشاف" },
  viewInvitation: { en: "My Invitation", ar: "دعوتي" },

  // story
  storyTitle: { en: "Our Story", ar: "قصتنا" },

  // gallery
  momentsTitle: { en: "Moments", ar: "لحظات" },
  all: { en: "All", ar: "الكل" },
  engagement: { en: "Engagement", ar: "الخطوبة" },
  henna: { en: "Henna", ar: "الحنة" },
  wedding: { en: "Wedding", ar: "الزواج" },
  other: { en: "Other", ar: "أخرى" },
  noPhotos: { en: "No photos yet.", ar: "لا توجد صور بعد." },

  // events
  whenWhere: { en: "When & Where", ar: "المكان والتوقيت" },
  ceremony: { en: "The Ceremony", ar: "حفل الزواج" },
  reception: { en: "The Reception", ar: "حفل الاستقبال" },
  addToCalendar: { en: "Add to Calendar", ar: "أضف إلى التقويم" },
  openMap: { en: "Open in Maps", ar: "افتح في الخرائط" },

  // invite
  youAreInvited: { en: "You are warmly invited", ar: "يسعدنا دعوتكم" },
  reservedSeats: { en: "Reserved seats", ar: "مقاعد محجوزة" },
  seats: { en: "seats", ar: "مقاعد" },
  scanAtEntrance: {
    en: "Show this QR code at the entrance",
    ar: "اعرض رمز الاستجابة السريعة عند المدخل",
  },
  willAttend: { en: "Joyfully Accept", ar: "بكل سرور، سأحضر" },
  cantAttend: { en: "Regretfully Decline", ar: "بأسف، لن أستطيع" },
  thanksConfirmed: {
    en: "Thank you — your attendance is confirmed.",
    ar: "شكرًا لكم — تم تأكيد حضوركم.",
  },
  thanksDeclined: {
    en: "Your response was received. You will be missed.",
    ar: "تم استلام ردكم. سنفتقدكم.",
  },
  family: { en: "Family of", ar: "عائلة" },
  notFound: { en: "Invitation not found.", ar: "لم يتم العثور على الدعوة." },
  personalLink: { en: "This invitation is personalized for your family.", ar: "هذه الدعوة خاصة بعائلتك." },

  // check-in
  checkIn: { en: "Check-in", ar: "تسجيل الحضور" },
  checkedIn: { en: "Checked in", ar: "تم الحضور" },
  markCheckedIn: { en: "Mark as Checked In", ar: "تسجيل الحضور الآن" },
  alreadyCheckedIn: { en: "Already checked in", ar: "مسجّل مسبقًا" },
  checkInSuccess: { en: "Welcome! Checked in successfully.", ar: "أهلًا بكم! تم تسجيل الحضور بنجاح." },

  // misc
  poweredBy: { en: "Generated by gencode", ar: "من إعداد gencode" },
} as const;

export type DictKey = keyof typeof dict;

export function t(key: DictKey, lang: Lang): string {
  return dict[key][lang];
}

export function bi(
  obj: { en?: string | null; ar?: string | null },
  lang: Lang
): string {
  return (lang === "ar" ? obj.ar || obj.en : obj.en || obj.ar) ?? "";
}
