"use client";

import Link from "next/link";
import { Languages, Heart } from "lucide-react";
import { useUi } from "@/store/ui";

export function SiteHeader({ monogram }: { monogram: string }) {
  const language = useUi((s) => s.language);
  const toggleLanguage = useUi((s) => s.toggleLanguage);

  const links = [
    { href: "#story", label: { en: "Our Story", ar: "قصتنا" } },
    { href: "#memories", label: { en: "Memories", ar: "ذكرياتنا" } },
    { href: "#details", label: { en: "Details", ar: "التفاصيل" } },
    { href: "#invitation-note", label: { en: "Invitation", ar: "الدعوة" } },
  ];

  return (
    <header
      className="fixed top-0 z-40 w-full border-b backdrop-blur-md"
      style={{ borderColor: "color-mix(in srgb, var(--t-outline-variant) 45%, transparent)", background: "var(--header-bg)" }}
    >
      <div className="container-wedding flex items-center justify-between py-3">
        <Link href="/demo" className="font-display text-xl tracking-wide text-primary md:text-2xl">
          {monogram}
        </Link>

        <nav className="hidden items-center gap-7 md:flex">
          {links.map((link) => (
            <a
              key={link.href}
              href={link.href}
              className="text-label-caps text-on-surface-variant transition-colors hover:text-primary"
            >
              {link.label[language]}
            </a>
          ))}
        </nav>

        <button
          type="button"
          onClick={toggleLanguage}
          className="text-label-caps flex cursor-pointer items-center gap-2 rounded-full border px-3 py-1.5 transition-colors"
          style={{ borderColor: "var(--t-outline-variant)", color: "var(--t-primary)" }}
          aria-label="Toggle language"
        >
          <Languages className="size-3.5" />
          {language === "en" ? "العربية" : "English"}
        </button>
      </div>
    </header>
  );
}

export function SiteFooter({ names }: { names: string }) {
  const language = useUi((s) => s.language);
  return (
    <footer
      className="section-gap text-center"
      style={{ borderTop: "1px solid color-mix(in srgb, var(--t-outline-variant) 40%, transparent)" }}
    >
      <div className="container-wedding flex flex-col items-center gap-4">
        <Heart className="size-4 text-primary" />
        <p className="font-display text-2xl text-primary">{names}</p>
        <p className="text-label-caps opacity-50">Generated by gencode</p>
        <span className="sr-only">{language}</span>
      </div>
    </footer>
  );
}
